### ISSUE TITLE
Instruction missing

### ISSUE THREAD

**Issue by weihua916** [ogb-visnet/Global-ViSNet#1]
Hi! Thank you for your OGB-LSC leaderboard submission!

In `README.md`, only an installation guide is provided. Please provide step-by-step instructions on how to run your code. Thanks!

**Comment by v-shaoningli** [comment]
Hi! We will finish the instructions right now.

And we made a mistake when submitting the leaderboard. The validation MAE is 0.0784 instead of 0.7840, but the next version can only be resubmitted next week. Could u please help to change this value?  Sorry for the trouble we caused.

Thanks!

**Comment by weihua916** [comment]
Thanks. Done!
